# Generated by Django 4.0.4 on 2022-04-24 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0003_rename_user_deck_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deck',
            options={'ordering': ['id']},
        ),
    ]
